### ISSUE TITLE
As a user, I want to be able to create a new journal entry

### ISSUE THREAD

**Issue by halfpintutopia** [halfpintutopia/mindful-minutes#11]
Epic: #2

### Tasks
- [ ] Design and implement a journal entry form
- [ ] Create a database model for journal entries
- [ ] Implement backend logic to retrieve journal entries from the database
- [ ] Add options to edit and delete journal entries
- [ ] Design and implement a journal entry detail for viewing and editing individual entries
