### ISSUE TITLE
As a user, I want to be able to categorise and tag my journal entries

### ISSUE THREAD

**Issue by halfpintutopia** [halfpintutopia/mindful-minutes#12]
Epic: #2 

### Tasks
- [ ] Design and implement a category and tag system
- [ ] Create database models for categories and tags
- [ ] Implement functionality to assign categories and tags to journal entries
- [ ] Add options to filter and search journal entries based on categories and tags
