### ISSUE TITLE
View and manage goals

### ISSUE THREAD

**Issue by halfpintutopia** [halfpintutopia/mindful-minutes#15]
Epic: #3 

### Description
As a **user**, I want to be able to **view and manage my goals** to **remain motivated and accountable**

### Tasks
- [x] Design and implement a goal management page
- [x] Create functionality to display a list of goals
- [x] Implement backend logic to retrieve goals from the database
- [x] Add options to edit, delete and mark goals as completed
- [x] Design and implement a goal detail page for viewing and editing individuals' goals
